$(document).ready(function() {

    if ($('#view').val() == 'event')
    {
        if ($(document).width() > 500)
        {
            var height = $(window).height();
            document.getElementById('main-info').style.minHeight=height*0.5+"px";
            document.getElementById('main-info').style.maxHeight=height*0.5+"px";
            document.getElementById('main-info').style.overflow="auto";
        }

        $('#main-info').fadeIn();

        $('#contact-no-form').bootstrapValidator({
            live:'enabled',
            submitButtons: 'button[id="contact-no-submit"]',
            message: 'This value is not valid',
            fields: {
                contactNo: {
                    message: 'The contact number is not valid',
                    validators: {
                        notEmpty: {
                            message: 'This field cannot be empty.'
                        },
                        integer: {
                            message: 'The value has to be a number'
                        },
                        stringLength: {
                            min: 10,
                            max: 10,
                            message: 'It has to be a 10-digit number'
                        }
                    }
                }
            }
        });

        $('#contact-no-form').submit(function(event)
        {
            event.preventDefault();
        });
    }
    else if ($('#view').val() == 'manageEvents')
    {
        /*oTableHosted=$('#hostedEvents').dataTable( {
            "ajax": 'http://localhost/b2v2/getHostedEvents',
            "lengthMenu": [[2, 10, 15, -1], [2, 10, 15, "All"]]
        } );

        oTableRegistered=$('#registeredEvents').dataTable( {
            "ajax": 'http://localhost/b2v2/getRegisteredEvents',
            "lengthMenu": [[2, 10, 15, -1], [2, 10, 15, "All"]]
        } );*/
    }
    else if ($('#view').val() == 'updateEvent')
    {
        $('#datetimepicker').datetimepicker();

        function validateUpdateEditor() {
            // Revalidate the content when its value is changed by Summernote
            $('#updateEventForm').bootstrapValidator('revalidateField', 'description');
        }

        $('#updateEventForm').bootstrapValidator({
            live:'enabled',
            submitButtons: 'button[id="updateEventSubmit"]',
            message: 'This value is not valid',
            excluded: [':disabled'],
            fields: {
                uploadCover: {
                    message: 'The cover pic is not valid',
                    validators: {
                        file: {
                            type: 'image/jpeg,image/jpg,image/png,image/gif',
                            maxSize: 2048 * 1024,   // 2 MB
                            message: '  Max 2MB, allowed types: JPG,PNG or GIF.'
                        }
                    }
                },
                title: {
                    validators: {
                        notEmpty: {
                            message: 'Please enter a title.'
                        },
                        stringLength: {
                            min: 1,
                            max: 255,
                            message: 'The title must be at least a character and less than 255 characters.'
                        }
                    }
                },
                description: {
                    validators: {
                        callback: {
                            message: 'Please talk about your event in a minimum of 140 words.',
                            callback: function(value, validator) {
                                var code = $('[name="description"]').code();
                                // <p><br></p> is code generated by Summernote for empty content
                                return (code !== '' && code !== '<p><br></p>' && code.length > 139);
                            }
                        }
                    }
                },
                venue: {
                    validators: {
                        notEmpty: {
                            message: 'Please enter a venue.'
                        },
                        stringLength: {
                            min: 1,
                            max: 255,
                            message: 'The venue name must be at least a character and less than 255 characters.'
                        }
                    }
                },
                category: {
                    validators: {
                        notEmpty: {
                            message: 'Please select a category.'
                        }
                    }
                },
                ifc: {
                    validators: {
                        notEmpty: {
                            message: 'Please specify IFC amount.'
                        },
                        integer: {
                            message: 'Number!'
                        },
                        between: {
                            min: 0,
                            max: 10000,
                            message: 'Less than 10000i.'
                        }
                    }
                },
                date: {
                    validators: {
                        notEmpty: {
                            message: 'Please select a date.'
                        }
                    }
                },
                time: {
                    validators: {
                        notEmpty: {
                            message: 'Please select a time.'
                        }
                    }
                },
                prerequesite: {
                    validators: {
                        notEmpty: {
                            message: 'This field cannot be empty.'
                        }
                    }
                },
                takeaway: {
                    validators: {
                        notEmpty: {
                            message: 'This field cannot be empty.'
                        }
                    }
                }
            }
        })
        .find('[name="description"]')
        .summernote({
            height: 300,
            onkeyup: function() {
                validateUpdateEditor();
            },
            onpaste: function() {
                validateUpdateEditor();
            },
            onfocus: function(e) {
                if ($('#summernote').code() == 'Description')
                    $('#summernote').code('');
            }
        });
    }
    else
    {
        $('#datetimepicker').datetimepicker();

        function validateEditor() {
            // Revalidate the content when its value is changed by Summernote
            $('#createEventForm').bootstrapValidator('revalidateField', 'description');
        }

        $('#createEventForm').bootstrapValidator({
            live:'enabled',
            submitButtons: 'button[id="createEventSubmit"]',
            message: 'This value is not valid',
            excluded: [':disabled'],
            fields: {
                uploadCover: {
                    message: 'The cover pic is not valid',
                    validators: {
                        file: {
                            type: 'image/jpeg,image/jpg,image/png,image/gif',
                            maxSize: 2048 * 1024,   // 2 MB
                            message: '  Max 2MB, allowed types: JPG,PNG or GIF.'
                        },
                        notEmpty: {
                            message: 'Please select an Event cover.'
                        }
                    }
                },
                title: {
                    validators: {
                        notEmpty: {
                            message: 'Please enter a title.'
                        },
                        stringLength: {
                            min: 1,
                            max: 255,
                            message: 'The title must be at least a character and less than 255 characters.'
                        }
                    }
                },
                description: {
                    validators: {
                        callback: {
                            message: 'Please talk about your event in a minimum of 140 words.',
                            callback: function(value, validator) {
                                var code = $('[name="description"]').code();
                                // <p><br></p> is code generated by Summernote for empty content
                                return (code !== '' && code !== '<p><br></p>' && code.length > 139);
                            }
                        }
                    }
                },
                venue: {
                    validators: {
                        notEmpty: {
                            message: 'Please enter a venue.'
                        },
                        stringLength: {
                            min: 1,
                            max: 255,
                            message: 'The venue name must be at least a character and less than 255 characters.'
                        }
                    }
                },
                category: {
                    validators: {
                        notEmpty: {
                            message: 'Please select a category.'
                        }
                    }
                },
                ifc: {
                    validators: {
                        notEmpty: {
                            message: 'Please specify IFC amount.'
                        },
                        integer: {
                            message: 'Number!'
                        },
                        between: {
                            min: 0,
                            max: 10000,
                            message: 'Less than 10000i.'
                        }
                    }
                },
                date: {
                    validators: {
                        notEmpty: {
                            message: 'Please select a date.'
                        }
                    }
                },
                time: {
                    validators: {
                        notEmpty: {
                            message: 'Please select a time.'
                        }
                    }
                },
                prerequesite: {
                    validators: {
                        notEmpty: {
                            message: 'This field cannot be empty.'
                        }
                    }
                },
                takeaway: {
                    validators: {
                        notEmpty: {
                            message: 'This field cannot be empty.'
                        }
                    }
                }
            }
        })
        .find('[name="description"]')
        .summernote({
            height: 300,
            onkeyup: function() {
                validateEditor();
            },
            onpaste: function() {
                validateEditor();
            },
            onfocus: function(e) {
                if ($('#summernote').code() == 'Description')
                    $('#summernote').code('');
            }
        });

        /*$('#createEventForm').submit(function(event)
        {
            $('#createEventSubmit').hide();
            $('#waiting').fadeIn();
        });*/
    }
});

function changeEventCover()
{
    var selectedImg = $('#uploadCover')[0].files[0];

    if (selectedImg != null)
    {
        var previewId = document.getElementById('defaultCover');
        previewId.src = '';

        var oReader = new FileReader();
        oReader.onload = function(e)
        {
            previewId.src=e.target.result;
        }
        oReader.readAsDataURL(selectedImg);
    }
}

function plusRegister()
{

    $.post('http://localhost/b2v2/getIFCs', function(ifc)
    {
        if(ifc=='wH@tS!nTheB0x')
            window.location='http://localhost/b2v2/offline';
        else
        {
            var eventIFCs = $('#ifcs').html();
            eventIFCs = parseInt(eventIFCs);
            ifc = parseInt(ifc);


            $('#ifcPurchasingModal').modal('show');


            var link="it";

            var content=false;

            $.ajax({
                type: "POST",
                url: 'http://localhost/b2v2/ifcModal/'+eventIFCs,
                data: {link:link,content:content},
                beforeSend: function()
                {
                    $("#ifcWaiting").show();

                }
            }).done(function(response)
            {
                if(response=='wH@tS!nTheB0x')
                    window.location='http://localhost/b2v2/offline';
                else
                {
                    $("#ifcWaiting").hide();
                    $("#ifcPurchasingModalBody").html(response);
                    $("#ifcPurchaseModalButtons").show();

                    if (ifc < eventIFCs)
                    {
                        $("#purchaseButton").html("Get IFC");
                    }
                }
            });
        }
    });
}

function checkForPurchase()
{
    if($('#purchaseButton').html()=='Get IFC')
    {
        window.location='http://localhost/b2v2/ifcDeficit';
    }
    else
    {
        $('#contact-details-modal').modal('show');
        $('#contact-no').focus();
    }
}

function register()
{
    var number = $('#contact-no').val();
    number = parseInt(number);

    var id = $('#event-id').val();
    id = parseInt(id);

    $('#contact-no-submit').hide();
    $('#waiting-one').fadeIn();

    $.post('http://localhost/b2v2/eventRegister', {id: id, number: number}, function(response)
    {
        if(response=='wH@tS!nTheB0x')
            window.location='http://localhost/b2v2/offline';
        if (response == 'success')
        {
            $('#waiting-one').hide();
            $('#contact-no-submit').fadeIn();
            $('#contact-no').val('');
            $('#contact-details-modal').modal('hide');
            bootbox.alert('Pack your bags, you are attending an event!');
            $('#plus-register').hide();
            $('#cancel-register').fadeIn();
            var attendees = $('#attendees').html();
            attendees = parseInt(attendees);
            attendees++;
            $('#attendees').html(attendees);
        }
    });
}

function cancelRegister()
{
    var message = 'Are you sure? You\'ll be dropped from the guest list and your IFCs won\'t be refunded either.';
    bootbox.confirm(message, function(result) {
        if (result==true)
        {
            $('#cancel-register').hide();
            $('#waiting-two').fadeIn();

            var id = $('#event-id').val();
            id = parseInt(id);

            $.post('http://localhost/b2v2/cancelRegister', {id: id}, function(response)
            {
                if(response=='wH@tS!nTheB0x')
                    window.location='http://localhost/b2v2/offline';
                if (response == 'success')
                {
                    bootbox.alert('Done, all you got is free time now!');
                    $('#waiting-two').hide();
                    $('#plus-register').fadeIn();
                    var attendees = $('#attendees').html();
                    attendees = parseInt(attendees);
                    attendees--;
                    $('#attendees').html(attendees);
                }
            });
        }
    });
}

function deleteEvent(id)
{
    bootbox.confirm('Are you sure', function(result) {
        if (result==true)
        {
            $.post('http://localhost/b2v2/deleteEvent', {id: id}, function(response)
            {
                if(response=='wH@tS!nTheB0x')
                    window.location='http://localhost/b2v2/offline';
                if (response == 'success')
                {
                    $('#Event'+id).fadeOut();
                }
            });
        }
    });
}

function toggleEvent(button,id)
{
    if (button.innerHTML == 'Close Registrations')
        var message = 'Are you sure to close the event registrations?';
    else
        var message = 'Are you sure to reopen the event registrations?';

    bootbox.confirm(message, function(result) {
        if (result==true)
        {
            $.post('http://localhost/b2v2/toggleEvent', {id: id}, function(response)
            {
                if(response=='wH@tS!nTheB0x')
                    window.location='http://localhost/b2v2/offline';
                if (response == 'success')
                {
                    if (button.innerHTML == 'Open Registrations')
                        button.innerHTML = 'Close Registrations';
                    else
                        button.innerHTML = 'Open Registrations';
                }
            });
        }
    });
}

function cancelRegisterMY(id)
{
    var message = 'Are you sure? You\'ll be dropped from the guest list and your IFCs won\'t be refunded either.';
    bootbox.confirm(message, function(result) {
        if (result==true)
        {
            $('#cancel-register-'+id).hide();
            $('#waiting').fadeIn();

            $.post('http://localhost/b2v2/cancelRegister', {id: id}, function(response)
            {
                if(response=='wH@tS!nTheB0x')
                    window.location='http://localhost/b2v2/offline';
                if (response == 'success')
                {
                    bootbox.alert('Done, all you got is free time now!');
                    $('#waiting').hide();
                    $('#Event'+id).fadeOut();
                }
            });
        }
    });
}

function mailMe(id)
{
    $('#mail-me').hide();
    $('.waiting').show();

    $.post('http://localhost/b2v2/mailMe', {id: id}, function(error)
    {
        if(error=='wH@tS!nTheB0x')
            window.location='http://localhost/b2v2/offline';
        else
        {
            $('.waiting').hide();
            $('#mail-me').show();
            bootbox.alert("Check your inbox!");
        }
    });
}